# use java support.
language: java
jdk:
  - oraclejdk8

# install the newest java.
addons:
  apt:
    packages:
      - oracle-java8-installer

sudo: false

os:
  - linux

services:
  - mongodb

# skip install stage.
install: true
  
# run gradle build/test
script:
  - cd api
  - gradle test
  - gradle jacocoTestReport
after_success:
  - bash <(curl -s https://codecov.io/bash)
