# use java support.
language: java
jdk:
  - oraclejdk8

# install the newest java.
addons:
  apt:
    packages:
      - oracle-java8-installer

sudo: false

os:
  - linux

services:
  - postgresql

# skip install stage.
install: true

before_script:
  - psql -c 'create database larbin;' -U postgres
  
# run gradle build/test
script:
  - cd Larbin-Api
  - gradle test
  - gradle jacocoTestReport
after_success:
  - bash <(curl -s https://codecov.io/bash)